try {
    let myString = 'test';
    console.log(myString.toUpperCase());
    console.log(0 / 2);
} catch {
    console.log("Error caught!");
}

console.log("Outside catch!");